Calvin's Pull request
Woodside-HS/Ecosystem-2023_24 pull request #9
Opened 2023-12-19 17:32 UTC by 812967

Predator 2 
- four snake arms reach out and grab prey within range of 100 pixels and then returns to creature 
- changes color over time 
- dies over time 
- eats predator 3 

Still needs to: 
- reproduce 
- snake arms can't reach prey more than once (eats a total of 4 times in its life)

2023-12-19 17:37 UTC, 810218 commented on main.js
> +  for(let i = 0; i<world.creatures.pred2.length; i++){
This should be in world.js

2023-12-19 17:40 UTC, 810218 requested changes
He needs to change the running of his predator from main.js to world.js

2023-12-19 17:41 UTC, 812967 commented
Predator 2
- four snake arms reach out and grab prey within range of 100 pixels and then returns to creature
- changes color over time
- dies over time
- eats predator 3

Still needs to:
- reproduce
- snake arms can't reach prey more than once (eats a total of 4 times in its life)

2024-01-12 17:52 UTC, anorakthegreat commented
Change everything. Quite spleindiferiousigenousiriditory

2024-01-12 18:15 UTC, 810636 commented
slay

2024-01-12 18:16 UTC, merged